#ifndef OASSETCONTAINER_H__
#define OASSETCONTAINER_H__

enum
{
	ASSETCONTAINER_SELECTION						= 1000,
		ASSETCONTAINER_SELECTION_NONE			= 0,
	ASSETCONTAINER_SOURCE								= 1001,
	ASSETCONTAINER_ADD									= 1002
};

#endif // OASSETCONTAINER_H__
