#ifndef OCIRCLESHAPE_H__
#define OCIRCLESHAPE_H__

enum
{
	SDK_EXAMPLE_CIRCLESHAPE_RADIUS = 1000,
	SDK_EXAMPLE_CIRCLESHAPE_VCOUNT = 1001,
	SDK_EXAMPLE_CIRCLESHAPE = 2000
};

#endif // OCIRCLESHAPE_H__
