CONTAINER ocircleshape
{
	NAME ocircleshape;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL SDK_EXAMPLE_CIRCLESHAPE_RADIUS 		{ UNIT METER; MIN 0.0; }
		LONG  SDK_EXAMPLE_CIRCLESHAPE_VCOUNT 		{ MIN 4; MAX 1000; }
	}
}
