#ifndef TOOLDISPLAYCONTROL_H__
#define TOOLDISPLAYCONTROL_H__

enum
{
	DISPLAYCONTROLTOOL_MODE			= 2000,
		PER_OBJECT								= 0,
		PER_VERTEX								= 2,
		PER_VERTEX_PER_POLYGON		= 3
};

#endif // TOOLDISPLAYCONTROL_H__
